### ISSUE TITLE
Possible to update to Frodo V4.2 ?

### ISSUE THREAD

**Issue by kamotswind** [OtherCrashOverride/frodo-go#1]
Looking here:
http://www.cebix.net/viewvc/cebix/Frodo4/CHANGES?revision=1.5&view=markup

The V4.2 version includes the BIOS files in the headers. This would make it easier for users to setup their SD card. Is there a technical reason that prevents this version from being used?

**Comment by OtherCrashOverride** [comment]
> The V4.2 version includes the BIOS files in the headers. 

I do not have a license to redistribute the C64 ROMs, otherwise I would be happy to "bake" them in the source code.

**Comment by kamotswind** [comment]
Ok. I'll work on forward-porting some of the bugfixes and submit a pull request.
